language: java

matrix:
  include:
    - os: linux
      dist: precise
      jdk: oraclejdk7
      env: TEST_SUITE=assemble test --tests '*SystemdJournalAppenderTest*'
    - os: linux
      jdk: oraclejdk8
      env: TEST_SUITE=build
    - os: linux
      jdk: openjdk8
      env: TEST_SUITE=build
    - os: linux
      jdk: oraclejdk9
      env: TEST_SUITE=build
    - os: linux
      jdk: openjdk10
      env: TEST_SUITE=build

script:
    - ./gradlew ${TEST_SUITE}

branches:
    - master
    - 1.x
